# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  hclfmt-job:
    runs-on: ubuntu-latest
    name: hclfmt-check-action
    steps:
      - name: Checkout repo
        uses: actions/checkout@master

      - name: Fail on malformatted files
        uses: devops-infra/action-format-hcl@master
        with:
          check: true
